namespace Core.Tests.Data
{
    using System.Linq;
    using System.Resources;
    using Alphacloud.Common.Core.Resources;
    using FluentAssertions;
    using Moq;
    using NUnit.Framework;

//// ReSharper disable InconsistentNaming

    [TestFixture]
    internal class EnumResourceBinderTests
    {
        [SetUp]
        public void SetUp()
        {
            _resourceMgr = new Mock<ResourceManager>();
            _resourceMgr.Setup(rm => rm.GetString("TestEnum_AutoGeneratedKey")).Returns("Auto-generated");
            _resourceMgr.Setup(rm => rm.GetString("resource")).Returns("custom");
        }


        [TearDown]
        public void TearDown()
        {
            _resourceMgr.Verify();
        }


//// ReSharper disable ResourceItemNotResolved

        private Mock<ResourceManager> _resourceMgr;

        private enum TestEnum : byte
        {
            NonDecoratedField = 0,

            [ResourceBinding] AutoGeneratedKey = 1,

            [ResourceBinding(Key = "resource")] CustomKey = 2
        }

        [Test]
        public void GetResourceKey_KeyIsSpecifiedInAttribute_UseCustomKey()
        {
            var fieldInfo = typeof (TestEnum).GetField("CustomKey");
            if (fieldInfo == null)
                Assert.Fail("Field not found");

            EnumResourceBinder.GetResourceKey(fieldInfo, new ResourceBindingAttribute {Key = "Custom"})
                .Should().Be("Custom");
        }


        [Test]
        public void GetResourceKey_NoKeySpecified_ShouldGenerateKeyFromEnumAndFieldName()
        {
            var field = typeof (TestEnum).GetField("AutoGeneratedKey");
            if (field == null)
                Assert.Fail("Field not found");

            EnumResourceBinder.GetResourceKey(field, new ResourceBindingAttribute()).Should().Be(
                "TestEnum_AutoGeneratedKey");
        }


        [Test]
        public void GetText()
        {
            _resourceMgr.Setup(rm => rm.GetString("resource")).Returns("Custom");
            EnumResourceBinder.GetString(_resourceMgr.Object, TestEnum.CustomKey).Should().Be("Custom");
        }


        [Test]
        public void SelectListFor_MissingResourceKey_ShouldUseMemberName()
        {
            var r = EnumResourceBinder.SelectionListFor<TestEnum>(_resourceMgr.Object, KeyGenerationStategy.FieldName);
            r.First(p => p.Value == "AutoGeneratedKey").Text.Should().Be("Auto-generated");
        }


        [Test]
        public void ShouldMapUsingFieldNameKeyType()
        {
            var r = EnumResourceBinder.LoadStrings<TestEnum>(_resourceMgr.Object, KeyGenerationStategy.FieldName);
            r.Count.Should().Be(2);
            r.Keys.Should().Contain("AutoGeneratedKey").And.Contain("CustomKey");
        }


        [Test]
        public void ShouldMapUsingNumberKeyType()
        {
            var r = EnumResourceBinder.LoadStrings<TestEnum>(_resourceMgr.Object, KeyGenerationStategy.NumericValue);
            r.Count.Should().Be(2);
            r.Keys.Should().Contain("1").And.Contain("2");
        }

//// ReSharper restore ResourceItemNotResolved
    }


//// ReSharper restore InconsistentNaming
}